"""Build ``case_data`` dicts for the PREPARE stage from raw upstream + HF metadata.

The PREPARE stage (:mod:`p3dbench.data.prepare`) turns a local raw upstream tree
(Fusion 360 Gallery + Text2CAD v1.1) plus the HuggingFace UID lists / annotations
into the per-case ``_shared_cache`` that :mod:`p3dbench.data.full_builder`
materializes. These loaders are the seam: each returns a ``case_data`` dict in the
shape the ported ``SharedDataCache.prepare_case`` consumes —

  * ``gt_step``          : a direct GT STEP path (Fusion image/assembly), OR
  * ``gt_minimal_json``  : a Text2CAD minimal-JSON path (text-to-3d; STEP is
                           generated by the shared interpreter), and optionally
  * ``text``             : the input/condition text (assembly caption / param text)
  * ``gt_parts``         : assembly per-part list ``[{part_id, role_name,
                           semantic, instance_count, step_path}]``.

Raw layout (verified, under ``--source-root``):
  fusion360/assembly/assembly/<uid>/assembly.step          (image-/assembly-3d union)
  fusion360/assembly/assembly/<uid>/<part_id>.step         (per-body, named by body UUID)
  text2cad/minimal_json/<bucket>/<id>/minimal_json/<id>.json
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def _assembly_dir(source_root: Path, uid: str) -> Path:
    return Path(source_root) / "fusion360" / "assembly" / "assembly" / uid


def build_image_case_data(uid: str, source_root: Path) -> Optional[dict]:
    """Image-to-3d: union STEP only (no text, no parts)."""
    step = _assembly_dir(source_root, uid) / "assembly.step"
    if not step.exists():
        logger.warning("image-to-3d %s: missing assembly.step", uid)
        return None
    return {"case_id": uid, "gt_step": str(step)}


def build_assembly_case_data(uid: str, source_root: Path,
                             hf_anno: Optional[dict]) -> Optional[dict]:
    """Assembly-3d: union STEP + assembly caption + per-part bodies.

    Per-part geometry is sourced by joining the HF ``part_level_annotations``
    ``part_id`` to the raw per-body STEP ``<uid>/<part_id>.step`` (verified exact
    across all 203 assemblies). Falls back to positional pairing if no part_id
    resolves, or geometry-only if there are no HF annotations.
    """
    udir = _assembly_dir(source_root, uid)
    step = udir / "assembly.step"
    if not step.exists():
        logger.warning("assembly-3d %s: missing assembly.step", uid)
        return None

    hf_anno = hf_anno or {}
    text = (hf_anno.get("assembly_level_annotation") or "").strip()
    part_annos = hf_anno.get("part_level_annotations") or []

    gt_parts, part_match = _resolve_assembly_parts(udir, part_annos)
    return {
        "case_id": uid,
        "text": text,
        "gt_step": str(step),
        "gt_parts": gt_parts,
        "part_match": part_match,
    }


def _resolve_assembly_parts(udir: Path, part_annos: list) -> tuple[list, str]:
    """Join HF part annotations to per-body STEPs. Returns (gt_parts, match_mode)."""
    def _entry(pa: dict, step_path: Path) -> dict:
        # HF ships `description_short` (no `semantic`); the manifest/metric use
        # `semantic` as the short per-part label, so map it here.
        semantic = (pa.get("description_short") or pa.get("description") or "").strip()
        return {
            "part_id": pa.get("part_id"),
            "role_name": pa.get("role_name", ""),
            "semantic": semantic,
            "instance_count": pa.get("instance_count", 1),
            "step_path": str(step_path),
        }

    # Primary: exact join on part_id -> <uid>/<part_id>.step
    if part_annos:
        resolved, missing = [], 0
        for pa in part_annos:
            pid = pa.get("part_id")
            sp = udir / f"{pid}.step" if pid else None
            if sp and sp.exists():
                resolved.append(_entry(pa, sp))
            else:
                missing += 1  # fallback A: drop this part class (keep the case)
        if resolved:
            if missing:
                logger.warning("%s: %d/%d parts had no body STEP (dropped)",
                               udir.name, missing, len(part_annos))
            return resolved, "part_id"

    # Fallback B: positional pairing of body STEPs (sorted) with annotations.
    body_steps = sorted(p for p in udir.glob("*.step") if p.name != "assembly.step")
    if part_annos and body_steps:
        logger.warning("%s: part_id join empty; positional pairing %d steps",
                       udir.name, len(body_steps))
        return ([_entry(pa, sp) for pa, sp in zip(part_annos, body_steps)], "positional")

    # Fallback C: geometry-only, no HF annotations.
    if body_steps:
        return ([{"part_id": sp.stem, "role_name": "", "semantic": "",
                  "instance_count": 1, "step_path": str(sp)} for sp in body_steps],
                "geometry_only")
    return [], "none"


def build_text_case_data(uid: str, source_root: Path,
                         hf_anno: Optional[dict]) -> Optional[dict]:
    """Text-to-3d: minimal-JSON program + parametric input text.

    The GT STEP/STL are generated from the minimal-JSON by the shared
    interpreter (not shipped), so only ``gt_minimal_json`` + ``text`` are needed.
    """
    if "/" not in uid:
        logger.warning("text-to-3d %s: malformed uid (want <bucket>/<id>)", uid)
        return None
    bucket, fid = uid.split("/", 1)
    mj = (Path(source_root) / "text2cad" / "minimal_json" / bucket / fid
          / "minimal_json" / f"{fid}.json")
    if not mj.exists():
        logger.warning("text-to-3d %s: missing minimal_json %s", uid, mj)
        return None

    hf_anno = hf_anno or {}
    text = (hf_anno.get("text_param") or "").strip()
    return {"case_id": uid, "text": text, "gt_minimal_json": str(mj)}
